// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Review struct {
	ID          int64   `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Reviewer    *User   `json:"reviewer"`
}

func (Review) IsEntity() {}

type ReviewListResponse struct {
	Reviews []*Review `json:"reviews"`
}

type User struct {
	ID          int64     `json:"id"`
	Reviews     []*Review `json:"reviews"`
	TotalReview *int      `json:"totalReview"`
}

func (User) IsEntity() {}
